version: 0.2

phases:
  install:
    commands:
      - echo Logging in to Amazon ECR in Seoul region...
      - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin ${ECR_REGISTRY}

  pre_build:
    commands:
      - echo Setting up yq...
      - wget -qO ~/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
      - chmod +x ~/yq
      - ~/yq --version

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t ${ECR_REGISTRY}/mylittlerecipebook/mlr-prd-be-img-ocr:${CODEBUILD_BUILD_NUMBER} -f Dockerfile .
      - echo "Docker build completed"
      - docker images

  post_build:
    commands:
      - echo Tagging the Docker image...
      - docker tag ${ECR_REGISTRY}/mylittlerecipebook/mlr-prd-be-img-ocr:${CODEBUILD_BUILD_NUMBER} ${ECR_REGISTRY}/mylittlerecipebook/mlr-prd-be-img-ocr:latest
      - echo "Docker image tagged"
      - echo Pushing the Docker image to Seoul region ECR...
      - docker push ${ECR_REGISTRY}/mylittlerecipebook/mlr-prd-be-img-ocr:${CODEBUILD_BUILD_NUMBER}
      - docker push ${ECR_REGISTRY}/mylittlerecipebook/mlr-prd-be-img-ocr:latest
      - echo "Docker push completed"
      - echo Updating be_ocr_deployment.yaml with the new image...
artifacts:
  files:
    - '**/*'
  discard-paths: yes
